In [1]:
import warnings
warnings.simplefilter("ignore")

## Escalamiento de los datos

In [3]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<div class="alert alert-success">
  Diversos algoritmos son sensibles a la escala en la que viene cada feature. **Re-escalarlos** puede traer significativas mejoras de rendimiento.
</div>

Existen distintas estrategias de escalamiento de tus features, pero **la más común es la estandarización** donde convertimos la variable para que la distribución de esta siga una distribución que es Gaussiana de media 0 y de desviación estandar 1.

In [4]:
from sklearn.model_selection import train_test_split

#X = pd.read_csv('../vol/intermediate_results/X.csv')
X = pd.read_csv('X.csv')
y = X['worldwide_gross']
X = X.drop('worldwide_gross',axis=1)
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [5]:
# PREPROCESSING
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [6]:
# los promedios de c/u de las features
scaler.mean_

array([3.34293486e+07, 2.00218055e+03, 2.12349130e+00, 1.08203717e+02,
       1.04586062e+04, 3.72997042e+07, 6.46046134e+00])

In [7]:
# desviacion standard
scaler.scale_

array([4.13953290e+07, 1.19684855e+01, 7.20578759e-01, 2.27383598e+01,
       2.00144270e+04, 6.58531187e+07, 1.06722362e+00])

In [8]:
X.values

array([[4.25000000e+08, 2.00900000e+03, 1.78000000e+00, ...,
        4.83400000e+03, 2.37000000e+08, 7.90000000e+00],
       [3.06000000e+08, 2.00213073e+03, 2.12697615e+00, ...,
        1.43000000e+02, 4.04553863e+07, 7.10000000e+00],
       [3.00000000e+08, 2.00700000e+03, 2.35000000e+00, ...,
        4.83500000e+04, 3.00000000e+08, 7.10000000e+00],
       ...,
       [7.00000000e+03, 2.00500000e+03, 2.12697615e+00, ...,
        9.30000000e+01, 3.25000000e+03, 7.80000000e+00],
       [3.96700000e+03, 2.01200000e+03, 2.35000000e+00, ...,
        2.38600000e+03, 4.04553863e+07, 6.30000000e+00],
       [1.10000000e+03, 2.00400000e+03, 1.85000000e+00, ...,
        1.63000000e+02, 1.10000000e+03, 6.60000000e+00]])

In [9]:
scaler.transform(X_train)

array([[-0.74475428,  0.15201973,  0.00483619, ..., -0.51360982,
         0.04792001,  1.34886319],
       [ 0.3278305 , -1.01771891, -0.37954393, ..., -0.41782891,
         0.95212341, -0.33775615],
       [-0.77132733,  0.23557249, -0.64322087, ..., -0.47963433,
        -0.54362959,  0.2244503 ],
       ...,
       [-0.73509136,  0.73688905,  0.31434274, ..., -0.46014838,
        -0.52085163, -0.33775615],
       [ 0.01378541, -0.18219131,  0.31434274, ..., -0.43371745,
        -0.05010703, -0.80626152],
       [ 0.11041467,  0.48623077,  0.31434274, ...,  0.2515882 ,
         0.26878447,  0.03704815]])

In [10]:
# TRANSFORMAR TODOS LOS DATOS 
X_train_scaled, X_test_scaled = (scaler.transform(X_train), scaler.transform(X_test))

In [11]:
from sklearn.linear_model import Lasso
# model normal
model = Lasso()
# modelo scalado
model_scaled = Lasso()

model.fit(X_train,y_train)
model_scaled.fit(X_train_scaled,y_train)

Lasso()

In [12]:
print(model.score(X_test,y_test))
print(model_scaled.score(X_test_scaled,y_test))

0.5659488355530882
0.5659488524114811


<div class="alert alert-success">
  Los modelos de regresión no se ven afectados por el escalamiento de las features. Los de clasificación sí. 
</div>

## Simplificar las transformaciones con pipelines

<div class="alert alert-info">
  Para hacer tu código más reproducible, y para evitar tener que aplicar multiples veces una misma transformación te recomendamos utilizar <code> sklearn.pipeline.make_pipeline </code> que permite encadenar transformaciones a tus modelos.
</div>

In [13]:
from sklearn.pipeline import make_pipeline

model_scaled = make_pipeline(StandardScaler(),
                            Lasso())

model_scaled.fit(X_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [15]:
print(model_scaled.score(X_test,y_test))

0.5659488524114811


## Crear nuevas features de forma automática

In [16]:
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
from sklearn.preprocessing import PolynomialFeatures

transformer = PolynomialFeatures(2)
transformer.fit_transform(A)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

``PolynomialFeatures`` transforma una matriz $(A1,A2)$ a $(1,A1,A2,A1^2,A1\cdot A2,A2^2)$

In [18]:
X.shape

(4104, 7)

In [19]:
# tranformamos a mayor numero de columnas
transformer = PolynomialFeatures(2)
transformer.fit_transform(X).shape

(4104, 36)

In [20]:
model_poly = make_pipeline(PolynomialFeatures(2),
                          Lasso())
model_poly.fit(X_train,y_train)
model_poly.score(X_test,y_test)

-3.1111346894886376

In [21]:
model = Lasso()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.5659488355530882

## Crear features categóricas

<div class="alert alert-success">
  En terminos de Machine Learning a las features que pueden tomar un número finito de valores se les llama categóricas. Ejemplos para esto són: género, páis, grado académico, etc.
</div>

Un mapeo del tipo $\{Perú, Chile, Colombia, Venezuela\} \rightarrow \{1, 2, 3, 4\}$ tiene el problema de asignarle un ordén a los valores posibles de la categoría. Este orden impacta de distintas maneras los algoritmos de Machine Learning, por ejemplo aquellos que dependen de la topología de $R^n$ y de la función de distancia entre puntos en este espacio, considerarán que ciertas categorías se encuentran más cercanas unas de otras, siendo que esto es generado puramente artificialmente por el encoding, y no por las datos per se. 

Para no introducir información falsa o erronéa en nuestro modelos existen formas más inteligentes de encodear nuestros datos.

_**Encoding one-hot**_

Este encoding consiste en asignarle una columna a cada categoría y rellenarla con 0 y 1 de la forma siguiente:

In [23]:
d = pd.DataFrame([['Chile','Colombia','Colombia','Venezuela'],['hombre','mujer','hombre','mujer']])
d = d.T
d.columns = pd.Index(['pais','genero']) # da nombre a las columnas
d

pais  genero
0      Chile  hombre
1   Colombia   mujer
2   Colombia  hombre
3  Venezuela   mujer

In [24]:
pd.get_dummies(d)

pais_Chile  pais_Colombia  pais_Venezuela  genero_hombre  genero_mujer
0           1              0               0              1             0
1           0              1               0              0             1
2           0              1               0              1             0
3           0              0               1              0             1

Sklearn también ofrece un objeto OneHotEncoder pero es un poco más díficil de utilizar, así que por criterios pedagogicos hemos elegido ``pd.get_dummies``. Sin embargo el objeto de sklearn tiene la ventaja de ser pipeable, por lo que es bueno considerarlo para ciertos casos de uso.

Cuantas columnas generaríamos con un one-hot encoding de nuestras features categóricas?
https://github.com/JuanPabloMF/datasets-platzi-course 

In [25]:
movies_obj = pd.read_csv('movies_obj.csv')

In [26]:
# VER CUANTAS CATEGORIAS HAY:
# pd.Series.nunique : Cuenta las unidades
movies_obj.apply(pd.Series.nunique).sort_values()

color                2
content_rating      18
language            47
country             65
genres             914
actor_1_name      2097
director_name     2398
actor_2_name      3032
actor_3_name      3521
plot_keywords     4760
movie_title       4917
dtype: int64

Las features más informativas son las del casting. Si embargo haciendo un one-hot encoding de estas estaríamos aumentando la dimensión por 2000 y algo!!

## Encoding Binario

Esta técnica no es canónica por lo que tendremos que buscarla en otra librería. Sin embargo el autor tuvo la buena idea de hacer su API compatible con la de sklearn, así que no tendremos ninguna dificultad en usarla.

$$ Categoria \rightarrow Numero \rightarrow Binario \rightarrow Columnas $$

In [29]:
!pip install category_encoders
!python -m pip install --upgrade pip

In [30]:
categoricals = pd.read_csv('intermediate_results/categoricals.csv').set_index('Unnamed: 0')

In [31]:
categoricals.head(6)

actor_1_name      director_name
Unnamed: 0                                    
0               CCH Pounder      James Cameron
1               Doug Walker        Doug Walker
2               Johnny Depp     Gore Verbinski
3           Christoph Waltz         Sam Mendes
4                 Tom Hardy  Christopher Nolan
5               Johnny Depp     Gore Verbinski

In [32]:
# reseteo el index y hanblin de valores faltantes con ceros
categoricals = categoricals.reset_index(drop=True).fillna(0)

In [37]:
X.head()

production_budget   title_year  aspect_ratio  duration.1  \
0        425000000.0  2009.000000      1.780000  178.000000   
1        306000000.0  2002.130733      2.126976  108.577186   
2        300000000.0  2007.000000      2.350000  169.000000   
3        300000000.0  2015.000000      2.350000  148.000000   
4        275000000.0  2012.000000      2.350000  164.000000   

   cast_total_facebook_likes        budget  imdb_score  
0                     4834.0  2.370000e+08         7.9  
1                      143.0  4.045539e+07         7.1  
2                    48350.0  3.000000e+08         7.1  
3                    11700.0  2.450000e+08         6.8  
4                   106759.0  2.500000e+08         8.5

In [38]:

X_binenc = pd.concat([X,categoricals],axis=1)

In [39]:
X_binenc.head()

production_budget   title_year  aspect_ratio  duration.1  \
0        425000000.0  2009.000000      1.780000  178.000000   
1        306000000.0  2002.130733      2.126976  108.577186   
2        300000000.0  2007.000000      2.350000  169.000000   
3        300000000.0  2015.000000      2.350000  148.000000   
4        275000000.0  2012.000000      2.350000  164.000000   

   cast_total_facebook_likes        budget  imdb_score     actor_1_name  \
0                     4834.0  2.370000e+08         7.9      CCH Pounder   
1                      143.0  4.045539e+07         7.1      Doug Walker   
2                    48350.0  3.000000e+08         7.1      Johnny Depp   
3                    11700.0  2.450000e+08         6.8  Christoph Waltz   
4                   106759.0  2.500000e+08         8.5        Tom Hardy   

       director_name  
0      James Cameron  
1        Doug Walker  
2     Gore Verbinski  
3         Sam Mendes  
4  Christopher Nolan

In [40]:
# CODIFICAR CATEGORIAS
import category_encoders as ce
encoder = ce.BinaryEncoder(cols=['actor_1_name','director_name'])

In [41]:
encoder.fit_transform(X_binenc).shape

(4104, 31)

In [42]:
X_binenc = encoder.fit_transform(X_binenc)

In [43]:
Xb_train, Xb_test, y_train, y_test = train_test_split(X_binenc,y)

In [44]:
X_train, X_test = (Xb_train[X.columns],Xb_test[X.columns])

In [45]:
model_binenc = Lasso()
model = Lasso()

In [46]:
model_binenc.fit(Xb_train,y_train)
model.fit(X_train,y_train)

Lasso()

In [47]:
print(model_binenc.score(Xb_test,y_test))
print(model.score(X_test,y_test))

0.51155716036857
0.5176042892651173


Aumentamos el rendimiento de nuestro algoritmo pero no de forma significativa. Mantengamos entonces la dimensionalidad de nuestro espacio de features baja, y vamos a buscar modelos más complejos.

## Conocimiento experto

<div class="alert alert-success">
  Una grán parte del diseño de las features pasa por un **conocimiento espécifico del dominio en el que se esta trabajando**. <br>
  Por ejemplo para analizar una imagen nuestro cerebro no se concentra en los millones de pixeles de una imagen, pero sólo en algunos relevantes como los de los contornos. Durante un buen tiempo **los sistemas de visión de computadores encodeaban features que traducían este conocimiento experto (contornos).** <br>
  Una de las únicas formas de obtener este conocimiento de forma sistemática es ir a bucear en repositorios de papers de Machine Learning como Arxiv, y estudiar la investigación que se ha hecho sobre el dominio específico.
</div>

## Más datos de calidad

Nada le gana conseguir más datos que sean encodeables en features de calidad.

_**Píramide de Maslow del Machine Learning**_

<img src="img/maslow.png">

Contamos con la base de datos de ganancias de las péliculas el primer fin de semana de exhibición, así como la cantidad de cines en la que fue estrenada.

In [48]:
pd.read_csv('opening_df.csv').head()

Unnamed: 0                  movie_title  opening_gross  screens
0           0       10 Days in a Madhouse          2451.0     10.0
1           1  10 Things I Hate About You       8330681.0   2271.0
2           2              102 Dalmatians      19883351.0   2704.0
3           3                   12 Rounds       5329240.0   2331.0
4           4            12 Years a Slave        923715.0     19.0

Puedes mejorar considerablemente nuestra predicción?